# Generated by Django 5.2.17 on 2026-09-19 13:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cgst",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="igst",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="sgst",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="state",
            field=models.CharField(default="Tamil Nadu", max_length=80),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_tax",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="gst_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="gst_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("5.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="gst_rate",
            field=models.DecimalField(
                choices=[
                    (Decimal("0.00"), "0% (Exempt)"),
                    (Decimal("5.00"), "5% GST (Apparel <= ₹1000)"),
                    (Decimal("12.00"), "12% GST (Apparel > ₹1000)"),
                    (Decimal("18.00"), "18% GST (Luxury / Accessories)"),
                    (Decimal("28.00"), "28% GST"),
                ],
                decimal_places=2,
                default=Decimal("5.00"),
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="Google Pay / UPI", max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_reference",
            field=models.CharField(
                blank=True, help_text="UPI Transaction ID / UTR", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Base price before GST or selling price",
                max_digits=10,
            ),
        ),
    ]
